[package]
name = "jingo-cli"
description = "A lightweight, high-level language designed for rapid prototyping"
publish = false
version = "0.1.0"
authors = ["Owez <root@ogriffiths.com>"]
license = "MIT"
repository = "https://github.com/owez/jingo"
readme = "../README.md"
edition = "2018"
