[package]
name = "jingo-lib"
description = "The central library for Jingo, containing the core of the compiler."
version = "0.1.0"
authors = ["Owez <owez@scalist.net>"]
edition = "2018"

[dependencies]
